"""
Django settings for TM_Manager project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a-0e5mer#yiiki2wvjsle$hnk1(*-5u+b1484j1u0&pwuetwsg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','*','https://f383-2409-40f3-100c-f34d-f91c-6d25-8ed3-4403.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'background_task',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TM_Manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TM_Manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'
CELERY_TIMEZONE = 'Asia/Kolkata'  # Same as Django's TIME_ZONE


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'api.Profile'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Update based on your email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'trackinn69@gmail.com'
EMAIL_HOST_PASSWORD = 'blrj rusd xofh xfhf'
# settings.py


import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#jazzmin admin pannel settings for customization

JAZZMIN_SETTINGS = {
    "site_title": "MedDox Admin",
    "site_header": "MedDox",
    "site_brand": "MedDox",
    "welcome_sign": "Welcome to MedDox Admin Dashboard",

    # Enable UI Builder
    "show_ui_builder": True,

    # Show a search bar in the top navigation
    "search_model": ["auth.User"],  # Enables search bar

    # Top navigation bar links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"], "new_window": False, "icon": "fas fa-home"},
        {"name": "Support", "url": "https://your-support-url.com", "new_window": True, "icon": "fas fa-life-ring"},
        {"name": "Users", "url": "admin:auth_user_changelist", "permissions": ["auth.view_user"], "icon": "fas fa-users"},
    ],

    # Icons for models
    "icons": {
        "api.License": "fas fa-id-card",  
        "api.Tender": "fas fa-file-contract",
        "auth.User": "fas fa-users",
        "auth.Group": "fas fa-users-cog",
        "api.Notification": "fas fa-bell",
        "api.Profile": "fas fa-user-circle",
        "api.PNDT_License": "fas fa-file-medical",
        "api.TenderManager": "fas fa-briefcase",
        "api.PersonalDetails": "fas fa-address-card",
        "api.Feedback": "fas fa-comment-dots",
        "api.RecentlyViewed": "fas fa-history",
    },

    # Default icons for parents & children
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-file-alt",

    # Show admin's profile image instead of default icon
    "user_avatar": "image",
    
    # Copyright text in the footer
    "copyright": "MedDox.",
}


